### ISSUE TITLE
你好！能否添加一个的字段

### ISSUE THREAD

**Issue by vxhly** [navyxie/bankcardinfo#18]
由于我们自己公司业务需求，还需要用到银行卡的 那个小图标，类似于这样的

![image](https://user-images.githubusercontent.com/17906558/70606753-1daf5e80-1c38-11ea-9a2a-d59373bd06c6.png)

至于图标嘛，其实我想了两个方案，方案一：字段里存放的是图标的 URL 地址；方案二：字段里面存放 svg 代码

大佬能否支持呢？

**Comment by navyxie** [comment]
icon建议使用者按需实现，因为涉及不同公司不同业务icon的样式及分辨率不同
