### ISSUE TITLE
广州农村商业银行股份有限公司匹配有问题

### ISSUE THREAD

**Issue by painkiller7** [navyxie/bankcardinfo#19]
{
    bankName: "广州农村商业银行股份有限公司",
    bankCode: "GZRCU",
    patterns: [{
      reg: /^(909810|940035|621522|622439)\d{12}$/g,
      cardType: "DC"
    }]
  }

广州农村商业银行股份有限公司的bankCode应该是GRCB，而GZRCU是贵州省农村信用社的bankCode。
909810|940035开头的银行卡号正则，匹配到的是贵州省农村信用社。

**Comment by navyxie** [comment]
广州农村商业银行股份有限公司的bankCode应该是GRCB，而GZRCU是贵州省农村信用社的bankCode。-- 这个bankCode你是从哪里取的？@painkiller7
