### ISSUE TITLE
您好,怎样在ionic2中使用啊?

### ISSUE THREAD

**Issue by Swing-Ming** [navyxie/bankcardinfo#6]
![6nn 0jq4v5q4 my4y rab](https://cloud.githubusercontent.com/assets/19317844/24434982/3d2520ac-1465-11e7-9b5d-52d77bb26e33.png)
![6nn 0jq4v5q4 my4y rab](https://cloud.githubusercontent.com/assets/19317844/24434992/4f263584-1465-11e7-819b-e9c05d9430f4.png)
这样使用不对吗?

**Comment by navyxie** [comment]
@Swing-Ming 建议放在后端使用.浏览器就直接引入这个文件,然后window.getBankBin
